"""initial schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-14 09:39:40.597482
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.Enum('GROUP', 'PRIVATE', name='class_type_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_selling', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits > 0', name='ck_package_type_credits_positive'),
    sa.CheckConstraint('duration_days > 0', name='ck_package_type_duration_positive'),
    sa.CheckConstraint('price >= 0', name='ck_package_type_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'TRAINER', 'STUDENT', name='role_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING_ACTIVATION', name='user_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_password_reset_token_hash')
    )
    op.create_index('ix_password_reset_user', 'password_reset', ['user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='student_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('import_source', sa.String(length=64), nullable=True),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_source', 'external_ref', name='uq_student_import_ref'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('photo_key', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot', postgresql.TSTZRANGE(), sa.Computed('tstzrange(starts_at, ends_at)', persisted=True), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.Enum('GROUP', 'PRIVATE', name='class_type_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', name='session_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('recurrence_id', sa.String(length=36), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('import_source', sa.String(length=64), nullable=True),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('trainer_id'), '='), (sa.column('slot'), '&&'), where=sa.text("status = 'SCHEDULED'"), using='gist', name='ex_class_session_trainer_no_overlap'),
    sa.CheckConstraint('capacity > 0', name='ck_class_session_capacity_positive'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_class_session_time_order'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_source', 'external_ref', name='uq_class_session_import_ref')
    )
    op.create_index('ix_class_session_recurrence', 'class_session', ['recurrence_id'], unique=False)
    op.create_index('ix_class_session_starts_at', 'class_session', ['starts_at'], unique=False)
    op.create_index('ix_class_session_trainer_starts', 'class_session', ['trainer_id', 'starts_at'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('need', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONVERTED', 'LOST', name='lead_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('converted_student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['user_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_student_id'], ['student.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_phone_created', 'lead', ['phone', 'created_at'], unique=False)
    op.create_table('progress_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_account.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_progress_photo_student_taken', 'progress_photo', ['student_id', 'taken_at'], unique=False)
    op.create_table('renewal_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('next_contact_date', sa.Date(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_renewal_contact_student', 'renewal_contact', ['student_id', 'contacted_at'], unique=False)
    op.create_table('student_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('package_type_id', sa.Integer(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credits_snapshot', sa.Integer(), nullable=False),
    sa.Column('class_type_snapshot', sa.Enum('GROUP', 'PRIVATE', name='class_type_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='package_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('balance_cached', sa.Integer(), nullable=False),
    sa.Column('import_source', sa.String(length=64), nullable=True),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_cached >= 0', name='ck_student_package_balance_non_negative'),
    sa.CheckConstraint('credits_snapshot > 0', name='ck_student_package_credits_positive'),
    sa.CheckConstraint('end_date >= start_date', name='ck_student_package_date_order'),
    sa.ForeignKeyConstraint(['package_type_id'], ['package_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_source', 'external_ref', name='uq_student_package_import_ref'),
    sa.UniqueConstraint('student_id', 'id', name='uq_student_package_student_id')
    )
    op.create_index('ix_student_package_student_status', 'student_package', ['student_id', 'status'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_package_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CANCELLED_INTIME', 'CANCELLED_LATE', 'ATTENDED', 'NO_SHOW', name='booking_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('booked_by_user_id', sa.Integer(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('attendance_marked_by', sa.Integer(), nullable=True),
    sa.Column('attendance_marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_reschedule_grace', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_marked_by'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booked_by_user_id'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_session.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id', 'student_package_id'], ['student_package.student_id', 'student_package.id'], name='fk_booking_package_belongs_to_student', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_package', 'booking', ['student_package_id'], unique=False)
    op.create_index('ix_booking_session_status', 'booking', ['class_session_id', 'status'], unique=False)
    op.create_index('ix_booking_student', 'booking', ['student_id'], unique=False)
    op.create_index('uq_booking_active_per_student_session', 'booking', ['class_session_id', 'student_id'], unique=True, postgresql_where=sa.text("status = 'BOOKED'"))
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_package_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'TRANSFER', name='payment_method_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'VOID', name='payment_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status <> 'CONFIRMED' OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)", name='ck_payment_confirmed_has_actor'),
    sa.CheckConstraint("status <> 'VOID' OR (voided_by IS NOT NULL AND voided_at IS NOT NULL AND btrim(coalesce(void_reason, '')) <> '')", name='ck_payment_void_has_actor_and_reason'),
    sa.CheckConstraint('amount >= 0', name='ck_payment_amount_non_negative'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_package_id'], ['student_package.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voided_by'], ['user_account.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_package', 'payment', ['student_package_id'], unique=False)
    op.create_index('ix_payment_status_confirmed_at', 'payment', ['status', 'confirmed_at'], unique=False)
    op.create_table('waitlist_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PROMOTED', 'CANCELLED', 'PROMOTION_FAILED', name='waitlist_status_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('promoted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_session.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['promoted_by_user_id'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waitlist_session_created', 'waitlist_entry', ['class_session_id', 'created_at', 'id'], unique=False)
    op.create_index('uq_waitlist_waiting_per_student_session', 'waitlist_entry', ['class_session_id', 'student_id'], unique=True, postgresql_where=sa.text("status = 'WAITING'"))
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_package_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.Enum('PACKAGE_SOLD', 'PACKAGE_RENEWED', 'BOOKING_DEDUCT', 'CANCEL_REFUND', 'ADMIN_ADJUST', 'PAYMENT_VOID', name='ledger_reason_enum', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason_code <> 'ADMIN_ADJUST' OR (note IS NOT NULL AND btrim(note) <> '')", name='ck_credit_ledger_admin_adjust_needs_note'),
    sa.CheckConstraint('delta <> 0', name='ck_credit_ledger_delta_non_zero'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_package_id'], ['student_package.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_ledger_package', 'credit_ledger', ['student_package_id', 'id'], unique=False)
    op.create_index('uq_credit_ledger_booking_deduct_per_booking', 'credit_ledger', ['booking_id'], unique=True, postgresql_where=sa.text("reason_code = 'BOOKING_DEDUCT'"))
    op.create_index('uq_credit_ledger_cancel_refund_per_booking', 'credit_ledger', ['booking_id'], unique=True, postgresql_where=sa.text("reason_code = 'CANCEL_REFUND'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_credit_ledger_cancel_refund_per_booking', table_name='credit_ledger', postgresql_where=sa.text("reason_code = 'CANCEL_REFUND'"))
    op.drop_index('uq_credit_ledger_booking_deduct_per_booking', table_name='credit_ledger', postgresql_where=sa.text("reason_code = 'BOOKING_DEDUCT'"))
    op.drop_index('ix_credit_ledger_package', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index('uq_waitlist_waiting_per_student_session', table_name='waitlist_entry', postgresql_where=sa.text("status = 'WAITING'"))
    op.drop_index('ix_waitlist_session_created', table_name='waitlist_entry')
    op.drop_table('waitlist_entry')
    op.drop_index('ix_payment_status_confirmed_at', table_name='payment')
    op.drop_index('ix_payment_package', table_name='payment')
    op.drop_table('payment')
    op.drop_index('uq_booking_active_per_student_session', table_name='booking', postgresql_where=sa.text("status = 'BOOKED'"))
    op.drop_index('ix_booking_student', table_name='booking')
    op.drop_index('ix_booking_session_status', table_name='booking')
    op.drop_index('ix_booking_package', table_name='booking')
    op.drop_table('booking')
    op.drop_index('ix_student_package_student_status', table_name='student_package')
    op.drop_table('student_package')
    op.drop_index('ix_renewal_contact_student', table_name='renewal_contact')
    op.drop_table('renewal_contact')
    op.drop_index('ix_progress_photo_student_taken', table_name='progress_photo')
    op.drop_table('progress_photo')
    op.drop_index('ix_lead_phone_created', table_name='lead')
    op.drop_table('lead')
    op.drop_index('ix_class_session_trainer_starts', table_name='class_session')
    op.drop_index('ix_class_session_starts_at', table_name='class_session')
    op.drop_index('ix_class_session_recurrence', table_name='class_session')
    op.drop_table('class_session')
    op.drop_table('trainer')
    op.drop_table('student')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index('ix_password_reset_user', table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_table('import_run')
    op.drop_table('announcement')
    op.drop_table('user_account')
    op.drop_table('package_type')
    # ### end Alembic commands ###
